spring:
  application:
    name: ace-calculator
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    streams:
      application-id: ace-calculator
      properties:
        processing.guarantee: at_least_once
        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde

app:
  topic:
    input: ${ACE_CALCULATOR_INPUT_TOPIC:A} #TODO: Bytt til domenespesifikt navn
    output: ${ACE_CALCULATOR_OUTPUT_TOPIC:B} #TODO: Bytt til domenespesifikt navn
